networks:
  frontend:
    external: true
services:
  ddb-proxy:
    image: ghcr.io/mrprimate/ddb-proxy:latest
    container_name: ddb-proxy
    networks:
      - frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ddb-proxy-http.entrypoints=web
      - traefik.http.routers.ddb-proxy-http.rule=Host(`ddb-proxy.home.bowenarrows.net`)
      - traefik.http.routers.ddb-proxy-https.entrypoints=websecure
      - traefik.http.routers.ddb-proxy-https.rule=Host(`ddb-proxy.home.bowenarrows.net`)
      - traefik.http.routers.ddb-proxy-https.tls=true
      - traefik.http.routers.ddb-proxy-https.tls.certresolver=cloudflare
      - traefik.http.routers.ddb-proxy-https.service=ddb-proxy-svc
      - traefik.http.services.ddb-proxy-svc.loadBalancer.server.port=3000
