pages:
  - name: Home
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    # hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 12h
            timezone: America/Chicago
            label: Missouri

          - type: calendar
            first-day-of-week: sunday

          - type: bookmarks
            groups:
              - title: Personal
                links:
                  - title: Gmail
                    icon: di:gmail
                    url: https://mail.google.com/mail/u/0/
                  - title: Amazon
                    icon: di:amazon
                    url: https://www.amazon.com/
                  - title: My GitHub
                    icon: di:github-light.png
                    url: https://github.com/BowenArrows2K
              - title: Entertainment
                color: 10 70 50
                links:
                  - title: Hulu
                    icon: di:hulu
                    url: https://www.hulu.com/
                  - title: Disney+
                    icon: di:disney-plus
                    url: https://www.disneyplus.com/
                  - title: YouTube
                    icon: di:youtube
                    url: https://www.youtube.com/
                  - title: Prime Video
                    icon: di:prime-video-alt-dark
                    url: https://www.amazon.com/gp/video/storefront
              - title: Anime
                color: 200 50 50
                links:
                  - title: Crunchyroll
                    icon: https://www.crunchyroll.com/build/assets/img/favicons/favicon-v2-96x96.png
                    url: https://www.crunchyroll.com/
                  - title: Hidive
                    icon: https://static.diceplatform.com/prod/original/dce.hidive/settings/HIDIVE_Logo_iOS_1024x1024_281_29.Y3YMf.vMQ59.png?ts=1727963356
                    url: https://www.hidive.com/
                  - title: MyAnimeList
                    icon: https://myanimelist.net/favicon.ico
                    url: https://myanimelist.net/animelist/Bowenarrows4K
                  

          - type: group
            widgets:
              - type: repository
                title: Homelab Repo
                repository: BowenArrows2K/svc-prod-01
                pull-requests-limit: 5
                issues-limit: 3
                commits-limit: 3
              - type: repository
                title: FVTT Module Repo
                repository: BowenArrows2K/bowenarrows-utils
                pull-requests-limit: 5
                issues-limit: 3
                commits-limit: 3

          - type: videos
            style: vertical-list
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

          # - type: rss
          #   limit: 10
          #   collapse-after: 3
          #   cache: 12h
          #   feeds:
          #     - url: https://selfh.st/rss/
          #       title: selfh.st
          #       limit: 4
          #     - url: https://ciechanow.ski/atom.xml
          #     - url: https://www.joshwcomeau.com/rss.xml
          #       title: Josh Comeau
          #     - url: https://samwho.dev/rss.xml
          #     - url: https://ishadeed.com/feed.xml
          #       title: Ahmad Shadeed

      - size: full
        widgets:
          - type: search
            search-engine: google
            new-tab: false
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}
          - type: split-column
            widgets:
            - type: monitor
              cache: 1m
              title: Services
              sites:
                - title: Authentik
                  url: https://authentik-prod-1.bowenarrows.net/
                  icon: di:authentik
                - title: Home Assistant
                  url: https://ha-prod-1.home.bowenarrows.net/
                  icon: di:home-assistant
                - title: Node Red
                  url: https://nodered-prod-1.home.bowenarrows.net/
                  icon: di:node-red
            - type: monitor
              cache: 1m
              title: Lab
              sites:
                - title: Proxmox
                  url: https://prx-prod-1.home.bowenarrows.net/
                  icon: di:proxmox
                - title: Portainer
                  url: https://port-prod-1.home.bowenarrows.net/
                  icon: di:portainer
                - title: Dockge
                  url: https://dockge-prod-1.home.bowenarrows.net/
                  icon: di:dockge
                - title: Uptime Kuma
                  url: https://kuma-prod-1.home.bowenarrows.net/
                  icon: di:uptime-kuma
                - title: CheckMK
                  url: https://mon-prod-1.home.bowenarrows.net/
                  icon: di:checkmk
                - title: Grafana
                  url: https://grafana-prod-1.home.bowenarrows.net/
                  icon: di:grafana
            - type: monitor
              cache: 1m
              title: Foundry
              sites:
                - title: FoundryVTT
                  url: https://vtt.home.bowenarrows.net/
                  icon: di:foundry-vtt.png
                - title: FoundryVTT 13
                  url: https://vtt13.home.bowenarrows.net/
                  icon: di:foundry-vtt.png
            - type: monitor
              cache: 1m
              title: Network
              sites:
                - title: Router
                  url: http://192.168.1.1/
                  icon: di:netgear
                - title: Pi-hole
                  url: https://pihole-prod-1.home.bowenarrows.net/admin
                  icon: di:pi-hole
                - title: Traefik Dashboard
                  url: https://traefik-prod-1.home.bowenarrows.net/
                  icon: di:traefik
            - type: monitor
              cache: 1m
              title: Web Utils
              sites:
                - title: Cloudflared - BowenArrows
                  url: https://one.dash.cloudflare.com/e96bcee05b9bdedfe0261ab679b9fa91/networks/tunnels/cfd_tunnel/f6bcff1d-4a56-41ec-864f-75d1a9b5f8fd/edit?tab=publicHostname
                  icon: di:cloudflare
                - title: Cloudflared - Unrelated
                  url: https://one.dash.cloudflare.com/e96bcee05b9bdedfe0261ab679b9fa91/networks/tunnels/cfd_tunnel/9605cc8b-7217-447a-ba40-a23e2dd53f9f/edit?tab=publicHostname
                  icon: di:cloudflare
              
          - type: docker-containers
            hide-by-default: false

          # - type: group
          #   widgets:
          #     - type: reddit
          #       subreddit: technology
          #       show-thumbnails: true
          #     - type: reddit
          #       subreddit: selfhosted
          #       show-thumbnails: true

  # Add more pages here:
  # - name: Your page name
  #   columns:
  #     - size: small
  #       widgets:
  #         # Add widgets here

  #     - size: full
  #       widgets:
  #         # Add widgets here

  #     - size: small
  #       widgets:
  #         # Add widgets here
