pages:
  - name: Home
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    # hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 12h
            timezone: America/Chicago
            label: Missouri

          - type: calendar
            first-day-of-week: sunday

          - type: bookmarks
            groups:
              - title: Personal
                links:
                  - title: Gmail
                    icon: sh:gmail
                    url: https://mail.google.com/mail/u/0/
                  - title: Amazon
                    icon: sh:amazon
                    url: https://www.amazon.com/
                  - title: My GitHub
                    icon: sh:github-light.png
                    url: https://github.com/BowenArrows2K
              - title: Entertainment
                color: 10 70 50
                links:
                  - title: Hulu
                    icon: sh:hulu
                    url: https://www.hulu.com/
                  - title: Disney+
                    icon: sh:disney-plus
                    url: https://www.disneyplus.com/
                  - title: YouTube
                    icon: sh:youtube
                    url: https://www.youtube.com/
                  - title: Prime Video
                    icon: sh:amazon-prime-video
                    url: https://www.amazon.com/gp/video/storefront
              - title: Anime
                color: 200 50 50
                links:
                  - title: Crunchyroll
                    icon: sh:crunchyroll
                    url: https://www.crunchyroll.com/
                  - title: Hidive
                    icon: https://static.diceplatform.com/prod/original/dce.hidive/settings/HIDIVE_Logo_iOS_1024x1024_281_29.Y3YMf.vMQ59.png?ts=1727963356
                    url: https://www.hidive.com/
                  - title: MyAnimeList
                    icon: https://myanimelist.net/favicon.ico
                    url: https://myanimelist.net/animelist/Bowenarrows4K

      - size: full
        widgets:
          - type: search
            search-engine: google
            new-tab: false
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}
          - type: videos
            title: Smosh
            collapse-after-rows: 2
            style: grid-cards
            channels:
              - UCYJPby9DRCteedh5tfxVbrw # Smosh Pit
              - UCJ2ZDzMRgSrxmwphstrm8Ww # Smosh Games
              - UCEyodonqP_80YrDvattntmw # Smosh Cast
              - UCPJHQ5_DLtxZ1gzBvZE99_g # Smosh Alike 
          - type: videos
            title: Tech
            collapse-after-rows: 2
            style: grid-cards
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UC9x0AN7BWHpCDHSm9NiJFJQ # Network Chuck
      
  - name: Homelab
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 12h
            timezone: America/Chicago
            label: Missouri
          - type: calendar
            first-day-of-week: sunday
          - type: group
            widgets:
              - type: repository
                title: Homelab Repo
                repository: BowenArrows2K/svc-prod-01
                pull-requests-limit: 5
                issues-limit: 3
                commits-limit: 3
              - type: repository
                title: FVTT Module Repo
                repository: BowenArrows2K/bowenarrows-utils
                pull-requests-limit: 5
                issues-limit: 3
                commits-limit: 3

      - size: full
        widgets:
          - type: search
            search-engine: google
            new-tab: false
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}
          - type: split-column
            widgets:
            - type: monitor
              cache: 1m
              title: Services
              sites:
                - title: Authentik
                  url: https://authentik-prod-1.bowenarrows.net/
                  icon: sh:authentik
                - title: Home Assistant
                  url: https://ha-prod-1.home.bowenarrows.net/
                  icon: sh:home-assistant
                - title: Node Red
                  url: https://nodered-prod-1.home.bowenarrows.net/
                  icon: sh:node-red
                - title: Proxmox
                  url: https://prx-prod-1.home.bowenarrows.net/
                  icon: sh:proxmox
                - title: Portainer
                  url: https://port-prod-1.home.bowenarrows.net/
                  icon: sh:portainer
            - type: monitor
              cache: 1m
              title: Monitoring
              sites:
                - title: Dockge
                  url: https://dockge-prod-1.home.bowenarrows.net/
                  icon: sh:dockge
                - title: Uptime Kuma
                  url: https://kuma-prod-1.home.bowenarrows.net/
                  icon: sh:uptime-kuma
                - title: Beszel
                  url: https://beszel-prod-1.home.bowenarrows.net/
                  icon: sh:beszel
                - title: Grafana
                  url: https://grafana-prod-1.home.bowenarrows.net/
                  icon: sh:grafana
            - type: monitor
              cache: 1m
              title: Network
              sites:
                - title: Router
                  url: http://192.168.1.1/
                  icon: sh:netgear
                - title: Pi-hole
                  url: https://pihole-prod-1.home.bowenarrows.net/admin
                  icon: sh:pi-hole
            - type: monitor
              cache: 1m
              title: Web Utils
              sites:
                - title: Cloudflared - BowenArrows
                  url: https://one.dash.cloudflare.com/e96bcee05b9bdedfe0261ab679b9fa91/networks/tunnels/cfd_tunnel/f6bcff1d-4a56-41ec-864f-75d1a9b5f8fd/edit?tab=publicHostname
                  icon: sh:cloudflare
          - type: docker-containers
            hide-by-default: false