networks:
  frontend:
    external: true
  backend:
    external: true
services:
  dockge-prod-1:
    image: louislam/dockge:1
    container_name: dockge-prod-1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/bowenarrows/projects/dockge/dockge-compose:/home/bowenarrows/projects/dockge/dockge-compose
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/bowenarrows/projects/dockge/dockge-compose
    networks:
      - frontend
      - backend
    labels:
      glance.name: Dockge
      glance.icon: si:docker
      glance.id: dockge-prod-1
      glance.url: https://dockge-prod-1.home.bowenarrows.net
      glance.description: Docker Compose GUI
      traefik.enable: true
      traefik.http.routers.dockge-prod-1-http.entrypoints: web
      traefik.http.routers.dockge-prod-1-http.rule: Host(`dockge-prod-1.home.bowenarrows.net`) || Host(`dockge-prod-1.bowenarrows.net`)
      traefik.http.routers.dockge-prod-1-https.entrypoints: websecure
      traefik.http.routers.dockge-prod-1-https.rule: Host(`dockge-prod-1.home.bowenarrows.net`) || Host(`dockge-prod-1.bowenarrows.net`)
      traefik.http.routers.dockge-prod-1-https.tls: true
      traefik.http.routers.dockge-prod-1-https.tls.certresolver: cloudflare
      traefik.http.routers.dockge-prod-1-https.service: dockge-prod-1-svc
      traefik.http.services.dockge-prod-1-svc.loadBalancer.server.port: 5001