networks:
  frontend:
    external: true
  backend:
    external: true
services:
  nodered-prod-1:
    image: nodered/node-red
    container_name: nodered-prod-1
    networks:
      - frontend
    # ports:
    #   - 1880:1880
    volumes:
      - node_red_data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered-prod-1-http.entrypoints=web"
      - "traefik.http.routers.nodered-prod-1-http.rule=Host(`nodered-prod-1.home.bowen-arrows.net`)"
      - "traefik.http.routers.nodered-prod-1-https.entrypoints=websecure"
      - "traefik.http.routers.nodered-prod-1-https.rule=Host(`nodered-prod-1.home.bowen-arrows.net`)"
      - "traefik.http.routers.nodered-prod-1-https.tls=true"
      - "traefik.http.routers.nodered-prod-1-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.nodered-prod-1-https.service=nodered-prod-1-svc"
      - "traefik.http.services.nodered-prod-1-svc.loadBalancer.server.port=1880"
    
    
volumes:
  node_red_data: {}
