acl internal {
    192.168.0.0/16;
    172.16.0.0/12;
};

options {
    forwarders {
        192.168.0.128;
        # 1.1.1.1;
        # 1.0.0.1;
    };
    allow-query { internal; };
};

zone "home.bowenarrows.net" IN {
    type master;
    file "/etc/bind/home-bowenarrows-net.zone";
};