http:
  routers:
    homeassistant-rtr:
      entryPoints: 
        - websecure
      rule: "Host(`ha-prod-1.home.bowenarrows.net`) || Host(`ha-prod-1.bowenarrows.net`)"
      service: homeassistant-svc
      tls:
        certResolver: cloudflare
    pihole-rtr:
      entryPoints:
        - websecure
      rule: "Host(`pihole-prod-1.home.bowenarrows.net`)"
      service: pihole-svc
      middlewares:
        - "pihole-redirectregex"
      tls:
        certResolver: cloudflare
    proxmox-rtr:
      entryPoints:
        - websecure
      rule: "Host(`prx-prod-1.home.bowenarrows.net`)"
      service: proxmox-svc
      tls:
        certResolver: cloudflare

  middlewares:
    pihole-redirectregex:
      redirectRegex:
        regex: "^https://pihole-prod-1.home.bowenarrows.net/(.*)"
        replacement: "https://pihole-prod-1.home.bowenarrows.net/${1}"


  services:
    homeassistant-svc:
      loadBalancer:
        servers:
        - url: http://192.168.1.132:8123
    pihole-svc:
      loadBalancer:
        servers:
        - url: http://192.168.1.129
    proxmox-svc:
      loadBalancer:
        servers:
        - url: https://192.168.1.130:8006