http:
  routers:
    pihole-rtr:
      entryPoints:
        - websecure
      rule: "Host(`pihole-prod-1.home.bowenarrows.net`)"
      service: pihole-svc
      middlewares:
        - "pihole-redirectregex"
      tls:
        certResolver: cloudflare
    proxmox-rtr:
      entryPoints:
        - websecure
      rule: "Host(`prx-prod-1.home.bowenarrows.net`)"
      service: proxmox-svc
      tls:
        certResolver: cloudflare

  middlewares:
    pihole-redirectregex:
      redirectRegex:
        regex: "^https://pihole-prod-1.home.bowenarrows.net/(.*)"
        replacement: "https://pihole-prod-1.home.bowenarrows.net/${1}"


  services:
    pihole-svc:
      loadBalancer:
        servers:
        - url: https://10.69.1.9
    proxmox-svc:
      loadBalancer:
        servers:
        - url: https://10.69.1.11:8006