---
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack-prod-1
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - ./config:/config
    networks:
      - frontend
      - backend
    # ports:
    #   - 6875:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.bookstack-prod-1-http.entrypoints=web"
      - "traefik.http.routers.bookstack-prod-1-http.rule=Host(`bookstack-prod-1.home.bowen-arrows.net`) || Host(`bookstack-prod-1.bowen-arrows.net`)"
      - "traefik.http.routers.bookstack-prod-1-https.entrypoints=websecure"
      - "traefik.http.routers.bookstack-prod-1-https.rule=Host(`bookstack-prod-1.home.bowen-arrows.net`) || Host(`bookstack-prod-1.bowen-arrows.net`)"
      - "traefik.http.routers.bookstack-prod-1-https.tls=true"
      - "traefik.http.routers.bookstack-prod-1-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.bookstack-prod-1-https.service=bookstack-prod-1-svc"
      - "traefik.http.services.bookstack-prod-1-svc.loadBalancer.server.port=80"

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack-mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD="toor1234"
      - MYSQL_DATABASE=${DB_DATABASE} #optional
      - MYSQL_USER=${DB_USERNAME} #optional
      - MYSQL_PASSWORD=${DB_PASSWORD} #optional
    volumes:
      - ./bsdb/config:/config
    networks:
      - backend
    # ports:
    #   - 3306:3306
    restart: unless-stopped