networks:
  tunnel:
    external: true
services:
  tunnel-prod-1:
    container_name: tunnel-prod-1
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    networks:
      tunnel:
        ipv4_address: 172.30.0.2
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}