---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Applications:
    - Authentik:
        icon: authentik.png
        href: https://authentik-prod-1.bowenarrows.net
        container: authentik-prod-1-server
        description: Open Source SSO Provider
        # widget:
        #     type: authentik
        #     url: http://authentik-prod-1-server:9000
        #     key: {{HOMEPAGE_VAR_AUTHENTIK_KEY}}
    - Home Assistant:
        icon: home-assistant.png
        href: https://ha-prod-1.home.bowenarrows.net/
        description: Home Automation Platform
    - Node Red:
        icon: node-red.png
        href: https://nodered-prod-1.home.bowenarrows.net/
        container: nodered-prod-1
        description: Flow Based Automation Platform
    
- Lab:
    - Proxmox:
        icon: proxmox.png
        href: https://prx-prod-1.home.bowenarrows.net/
        description: Virtualization Host
    - Portainer:
        icon: portainer.png
        href: https://port-prod-1.home.bowenarrows.net/
        container: port-prod-1
        description: Container Management
    - Dockge:
        icon: dockge.png
        href: https://dockge-prod-1.home.bowenarrows.net
        container: dockge-prod-1
        description: Docker Compose Mangement
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://kuma-prod-1.home.bowenarrows.net/
        container: kuma-prod-1
        description: Uptime Checker
    - CheckMK:
        icon: checkmk.png
        href: https://mon-prod-1.home.bowenarrows.net/
        container: mon-prod-1
        description: Monitoring Dashboard
    - Grafana:
        icon: grafana.png
        href: https://grafana-prod-1.home.bowenarrows.net/
        container: grafana-prod-1
        description: Metrics Dashboard

- Foundry:
    - FoundryVTT:
        icon: foundry-vtt.png
        href: https://vtt.home.bowenarrows.net/
        container: vtt-prod-1-foundry-1
        description: Roleplaying Game
    - FoundryVTT 13:
        icon: foundry-vtt.png
        href: https://vtt13.home.bowenarrows.net/
        container: vtt-eval-1-foundry-1
        description: Roleplaying Game

- Network:
    - Router:
        icon: netgear.png
        href: http://192.168.1.1/
        description: Network Router
    - Pi-hole:
        icon: pi-hole.png
        href: https://pihole-prod-1.home.bowenarrows.net/admin
        description: Local DNS & Ad Blocking
    - Traefik Dashboard:
        icon: traefik.png
        container: traefik-prod-1
        description: Reverse Proxy

- Web Utils:
    - Cloudflared - BowenArrows:
        icon: cloudflare.png
        href: https://one.dash.cloudflare.com/e96bcee05b9bdedfe0261ab679b9fa91/networks/tunnels/cfd_tunnel/f6bcff1d-4a56-41ec-864f-75d1a9b5f8fd/edit?tab=publicHostname
        container: tunnel-prod-1
        description: Cloudflare Tunnel
        widget:
            type: cloudflared
            accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACC_ID}} # from zero trust dashboard url e.g. https://one.dash.cloudflare.com/<accountid>/home/quick-start
            tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}} # found in tunnels dashboard under the tunnel name
            key: {{HOMEPAGE_VAR_CLOUDFLARE_API_KEY}} # api token with `Account.Cloudflare Tunnel:Read` https://dash.cloudflare.com/profile/api-tokens
    - Cloudflared - Unrelated:
        icon: cloudflare.png
        href: https://one.dash.cloudflare.com/e96bcee05b9bdedfe0261ab679b9fa91/networks/tunnels/cfd_tunnel/9605cc8b-7217-447a-ba40-a23e2dd53f9f/edit?tab=publicHostname
        description: Cloudflare Tunnel
        widget:
            type: cloudflared
            accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACC_ID}} # from zero trust dashboard url e.g. https://one.dash.cloudflare.com/<accountid>/home/quick-start
            tunnelid: 9605cc8b-7217-447a-ba40-a23e2dd53f9f # found in tunnels dashboard under the tunnel name
            key: {{HOMEPAGE_VAR_CLOUDFLARE_API_KEY}} # api token with `Account.Cloudflare Tunnel:Read` https://dash.cloudflare.com/profile/api-tokens
