networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  uptime-kuma: {}
services:
  uptime-kuma:
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - uptime-kuma:/app/data
    container_name: kuma-prod-1
    image: louislam/uptime-kuma:latest
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma-prod-1-http.entrypoints=web"
      - "traefik.http.routers.kuma-prod-1-http.rule=Host(`kuma-prod-1.home.bowen-arrows.net`) || Host(`kuma-prod-1.bowen-arrows.net`)"
      - "traefik.http.routers.kuma-prod-1-https.entrypoints=websecure"
      - "traefik.http.routers.kuma-prod-1-https.rule=Host(`kuma-prod-1.home.bowen-arrows.net`) || Host(`kuma-prod-1.bowen-arrows.net`)"
      - "traefik.http.routers.kuma-prod-1-https.tls=true"
      - "traefik.http.routers.kuma-prod-1-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.kuma-prod-1-https.service=kuma-prod-1-svc"
      - "traefik.http.services.kuma-prod-1-svc.loadBalancer.server.port=3001"