networks:
  backend:
    external: true

services:
  bind9:
    container_name: dns-prod-1
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/Chicago
    networks:
      - backend
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: always
    labels:
      glance.name: Bind9 DNS
      glance.icon: si:docker
      glance.id: dns-prod-1
      glance.description: Bind9 DNS server