networks:
  frontend:
    external: true
  backend:
    external: true
services:
  homepage-prod-1:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-prod-1
    environment:
        - "HOMEPAGE_VAR_CLOUDFLARE_ACC_ID=${HOMEPAGE_VAR_CLOUDFLARE_ACC_ID}"
        - "HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID=${HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}"
        - "HOMEPAGE_VAR_CLOUDFLARE_API_KEY=${HOMEPAGE_VAR_CLOUDFLARE_API_KEY}"
    #   - "HOMEPAGE_VAR_PORTAINER_KEY=${HOMEPAGE_VAR_PORTAINER_KEY}"
    #   - "HOMEPAGE_VAR_AUTHENTIK_KEY=${HOMEPAGE_VAR_AUTHENTIK_KEY}"
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./images:/app/public/images
      - ./icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-prod-1-http.entrypoints=web"
      - "traefik.http.routers.homepage-prod-1-http.rule=Host(`homepage-prod-1.home.bowen-arrows.net`) || Host(`homepage-prod-1.bowen-arrows.net`)"
      - "traefik.http.routers.homepage-prod-1-https.entrypoints=websecure"
      - "traefik.http.routers.homepage-prod-1-https.rule=Host(`homepage-prod-1.home.bowen-arrows.net`) || Host(`homepage-prod-1.bowen-arrows.net`)"
      - "traefik.http.routers.homepage-prod-1-https.tls=true"
      - "traefik.http.routers.homepage-prod-1-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.homepage-prod-1-https.middlewares=authentik-prod-1-middleware@file"
      - "traefik.http.routers.homepage-prod-1-https.service=homepage-prod-1-svc"
      - "traefik.http.services.homepage-prod-1-svc.loadBalancer.server.port=3000"
    networks:
      - frontend
      - backend
    restart: unless-stopped