networks:
  frontend:
    external: true

services:
  grafana-prod-1:
    image: grafana/grafana-enterprise
    container_name: grafana-prod-1
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=https://grafana-prod-1.home.bowenarrows.net
    # ports:
    #   - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana-prod-1-http.entrypoints=web"
      - "traefik.http.routers.grafana-prod-1-http.rule=Host(`grafana-prod-1.home.bowenarrows.net`) || Host(`grafana-prod-1.bowenarrows.net`)"
      - "traefik.http.routers.grafana-prod-1-https.entrypoints=websecure"
      - "traefik.http.routers.grafana-prod-1-https.rule=Host(`grafana-prod-1.home.bowenarrows.net`) || Host(`grafana-prod-1.bowenarrows.net`)"
      - "traefik.http.routers.grafana-prod-1-https.tls=true"
      - "traefik.http.routers.grafana-prod-1-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.grafana-prod-1-https.service=grafana-prod-1-svc"
      - "traefik.http.services.grafana-prod-1-svc.loadBalancer.server.port=3000"

volumes:
  grafana-storage: {}
